
pipeline {
    agent {
        label "$NODE"
    }
    stages {
        stage ("First stage") {
            steps {
                echo "First stage!"
                echo "End of stage"
            }
        }
          stage ("Second stage") {
            steps {
                echo "second stage!"
                echo "End of stage"
            }
        }
        
    }
}