
pipeline {
    agent {
        label "$NODE"
    }
    tools {
        nodejs "NODE22" //cle : identifiant de outil / version de outil (ne pas utiliser node de serveur par default. ) ce pipeline se fait sur node 22
    }
    options {
        withFolderProperties() // permet de utilsier les props de folder (${mail to})
        skipDefaultCheckout(true) // pas checkout tout de suite
    }
    stages {
        stage("Pre stage"){
           steps {
             script {
                if(params.event != 'push') {
                    currentBuild.currentResult = "ABORTED"
                    error("Must be a push event, was: " + params.event)
                }
                cleanWs() // clean workspace. avant build. 
                checkout scm // checkout apres clean (pull)
                echo "${NODE}"
                echo "${params.event}"
                echo "${params.delivery}"
                echo "${params.hook}"
                echo "${params.trigger}"
            }
           }
        }
        stage ("Prepare presentation artifacts") {
            steps {
                script {
                    try{
                        configFileProvider(
                            [configFile(fileId: 'toto-presentation-env', variable: 'ENV_FILE_PATH')]) {
                                echo "${ENV_FILE_PATH}"
                            sh('bash toto-jenkins/prepare-presentation.sh $ENV_FILE_PATH $TOTO_PRESENTATION_DEPLOY_DIR $TOTO_PRESENTATION_URL') //passer variable à shell de jenkins // ecrit shell / ""-> warning interpollation / pour sh utilsier ''./ bash: pour dire c'est un bash executable (pour la raison securité)
                        }
                    } catch(Exception ex) {
                        unstable("Error in stage ${env.STAGE}: " + ex.toString())

                    }
                }
                    
            }
        }
        stage("Deploy presentation"){
            when{
                expression {
                    return currentBuild.currentResult != "UNSTABLE";
                }
            }
            step {
                echo "In deploy stage"
            }
        }
    }
    post {
        always {
            script{
                if(params.report){
                    echo "Sending report..."
                  mail(to:"${MAIL_TO}", subject:"test sub", body:"Jenkins, ${BUILD_URL}, Build status : ${currentBuild.currentResult}, Job name: ${JOB_NAME}")
                } else {
                    echo "Report disabled, not sending report."
                }
            }
        }
    }
}