
pipeline {
    agent {
        label "$NODE"
    }

    tools {
        nodejs "NODE22" //cle : identifiant de outil / version de outil
    }
    stages {
        stage("Pre stage"){
           steps {
             script {
                if(params.event != 'push') {
                    currentBuild.currentResult = "ABORTED"
                    error("Must be a push event, was: " + params.event)
                }
            }
           }
        }
        stage ("Build presentation") {
            steps {
                sh('node -v') // ecrit shell / ""-> warning interpollation / pour sh utilsier ''.
                sh('npm -v')
                echo "${NODE}"
                echo "${params.event}"
                echo "${params.delivery}"
                echo "${params.hook}"
                echo "${params.trigger}"
            }
        }       
    }
}